import unittest

from newscli.article import DEFAULT_HEADERS, extract_readable_text


class TestArticleHeaders(unittest.TestCase):
    def test_accept_encoding_avoids_brotli(self) -> None:
        enc = (DEFAULT_HEADERS.get("Accept-Encoding") or "").lower()
        # Regression test: SG sites were returning brotli-encoded pages that
        # httpx couldn't decode without optional extras, producing garbled text.
        self.assertNotIn("br", enc)


class TestReadableText(unittest.TestCase):
    def test_plain_text_mirror_metadata_stripped(self) -> None:
        plain = (
            "Title: Example Mirror Title\n\n"
            "URL Source: http://example.com/article\n\n"
            "Published Time: Fri, 12 Dec 2025 07:32:20 GMT\n\n"
            "Markdown Content:\n"
            "![Alt](https://example.com/image.png)\n"
            "First paragraph.\n\n"
            "Second paragraph.\n"
        )
        content = extract_readable_text(plain)
        self.assertEqual(content.title, "Example Mirror Title")
        self.assertIn("First paragraph.", content.text)
        self.assertIn("Second paragraph.", content.text)
        self.assertNotIn("URL Source:", content.text)
        self.assertNotIn("Published Time:", content.text)
        self.assertNotIn("Markdown Content:", content.text)
        self.assertIn("https://example.com/image.png", content.images)

    def test_basic_html_extraction(self) -> None:
        html = (
            "<html><head>"
            "<title>Fallback</title>"
            "<meta property=\"og:image\" content=\"https://example.com/cover.jpg\"/>"
            "</head>"
            "<body><article><h1>Real Title</h1>"
            "<img src=\"/img/inline.png\" width=\"600\" height=\"400\"/>"
            "<p>This is a long enough paragraph to be included in extraction.</p>"
            "<p>Another sufficiently long paragraph for testing purposes.</p>"
            "</article></body></html>"
        )
        content = extract_readable_text(html, base_url="https://example.com/article")
        self.assertEqual(content.title, "Real Title")
        self.assertIn("long enough paragraph", content.text)
        self.assertIn("Another sufficiently long paragraph", content.text)
        self.assertIn("https://example.com/cover.jpg", content.images)
        self.assertIn("https://example.com/img/inline.png", content.images)

    def test_straits_times_boilerplate_removed(self) -> None:
        html = (
            "<html><body><article>"
            "<p>Sign up now: Get ST's newsletters delivered to your inbox</p>"
            "<p>Published Dec 12, 2025, 06:19 PM</p>"
            "<p>Updated Dec 12, 2025, 06:20 PM</p>"
            "<p>This is the real first paragraph of the story with enough length to be kept.</p>"
            "</article></body></html>"
        )
        content = extract_readable_text(html, base_url="https://www.straitstimes.com/singapore/test")
        self.assertNotIn("Sign up now", content.text)
        self.assertNotIn("Published Dec", content.text)
        self.assertNotIn("Updated Dec", content.text)
        self.assertIn("real first paragraph", content.text)

    def test_cna_audio_disclaimer_removed(self) -> None:
        html = (
            "<html><body><article>"
            "<p>This audio is generated by an AI tool.</p>"
            "<p>Actual content starts here and should remain in the output.</p>"
            "</article></body></html>"
        )
        content = extract_readable_text(html, base_url="https://www.channelnewsasia.com/test")
        self.assertNotIn("audio is generated", content.text.lower())
        self.assertIn("Actual content starts here", content.text)

    def test_mothership_nav_lines_removed_in_mirror(self) -> None:
        plain = (
            "Title: Example Mirror Title\n\n"
            "*   [News](http://mothership.sg/category/news)\n"
            "*   [Careers](http://mothership.sg/careers)\n"
            "==============\n"
            "The actual story starts here and should remain.\n"
        )
        content = extract_readable_text(plain, base_url="https://mothership.sg/2025/12/test")
        self.assertNotIn("category/news", content.text)
        self.assertNotIn("careers", content.text.lower())
        self.assertIn("actual story starts here", content.text.lower())


if __name__ == "__main__":
    unittest.main()
